// Generated by https://quicktype.io

export interface Result {
  ok: boolean;
  usuario: Usuario;
  msg: any;
  token: string;
}

export interface Login {
  email: string;
  password: string;
  remember: boolean;
}

export interface Usuario {}
