// Generated by https://quicktype.io

export interface Movies {
  ok: boolean;
  data: Datum[];
  msg: string;
}

export interface Datum {
  _id: string;
  name: string;
  desc: string;
  titleImage: string;
  image: string;
  category: string;
  language: string;
  year: number;
  time: number;
  video: Video[];
  rate: number;
  numberOfReviews: number;
  casts: any[];
  reviews: any[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Video {
  trailer: string;
  link: string;
}
